package drools.demo.project;

import drools.demo.project.Item;
import drools.demo.project.Item.Category;

rule "Classify Item as Low Range"
when
	$i: Item(cost < 200)
then
	System.out.println(kcontext.getRule().getName() + " fired!!!");
	modify($i){
		setCategory(Category.LOW_RANGE);
	}
end

rule "Apply discount on Low Range Item"
when
	$i: Item(category == Category.LOW_RANGE)
then
	System.out.println(kcontext.getRule().getName() + " fired!!!");
	modify($i){
		setSalePrice($i.getSalePrice()*0.9);
	}
end